default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  pool: 5
  database: xxx
  username: root
  password:
  host: localhost

development: &development
  <<: *default

development_sandbox:
  <<: *development

test: &test
  <<: *default

production: &production
  <<: *default

preview: &preview
  <<: *default
